CREATE TABLE `news` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` VARCHAR(255) DEFAULT NULL,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `details` TEXT,
  `media` TEXT,
  `title` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;