<?php
// Start the session
session_start();

// Include the database configuration file
include '../config/db.php'; // Adjust path as needed

// Include the functions file (if needed for any helper functions, e.g., validation)
include '../include/functions.php'; // Include the file containing connectDB()

// Check if the request method is POST
if ($_SERVER['REQUEST_METHOD'] == 'POST') {

    // Check if the 'action' parameter is set
    if (isset($_POST['action'])) {
        $action = $_POST['action'];

        // Get database connection
        $conn = connectDB(); // Assuming connectDB() function is available and returns connection

        // Check if database connection is successful
        if (!$conn) {
            $_SESSION['error_message'] = "ไม่สามารถเชื่อมต่อฐานข้อมูลเพื่อดำเนินการได้";
            // Redirect back to the manage semesters page
            // *** ตรวจสอบพาธนี้ให้ถูกต้องตามโครงสร้างโฟลเดอร์ของคุณ ***
            header("Location: ../admin/manage_semesters.php");
            exit();
        }

        switch ($action) {
            case 'add':
                // --- Handle Add Semester Action ---
                // Get data from the form (from manage_semesters.php)
                $semester_name = htmlspecialchars($_POST['semester_name'] ?? '');
                $start_date = htmlspecialchars($_POST['start_date'] ?? '');
                $end_date = htmlspecialchars($_POST['end_date'] ?? '');

                // Basic validation
                if (empty($semester_name) || empty($start_date) || empty($end_date)) {
                    $_SESSION['error_message'] = "กรุณากรอกข้อมูลภาคการศึกษาให้ครบถ้วน";
                } else {
                    // Prepare SQL query to insert a new semester into the 'semesters' table
                    // Ensure column names match your 'semesters' table: id, semester_name, start_date, end_date
                    // 'id' is typically auto-generated by the database
                    $insert_query = "INSERT INTO semester (semester_name, start_date, end_date) VALUES (?, ?, ?)";

                    // Prepare the statement
                    if ($stmt = $conn->prepare($insert_query)) {
                        // Bind parameters
                        // 'sss' indicates that all 3 parameters are strings (assuming DATE is treated as string for binding)
                        // Adjust types based on your database column types if needed (e.g., 'sdd' if using date objects)
                        $stmt->bind_param("sss", $semester_name, $start_date, $end_date);

                        // Execute the statement
                        if ($stmt->execute()) {
                            $_SESSION['success_message'] = "เพิ่มภาคการศึกษาสำเร็จแล้ว";
                        } else {
                            $_SESSION['error_message'] = "เกิดข้อผิดพลาดในการเพิ่มภาคการศึกษา: " . $stmt->error;
                        }

                        // Close statement
                        $stmt->close();
                    } else {
                        $_SESSION['error_message'] = "เกิดข้อผิดพลาดในการเตรียมคำสั่งฐานข้อมูล (เพิ่มภาคการศึกษา): " . $conn->error;
                    }
                }
                break;

            case 'edit':
                // --- Handle Edit Semester Action ---
                // Get data from the edit form (from edit_semester.php - will be created later)
                $semester_id = htmlspecialchars($_POST['semester_id'] ?? '');
                $updated_semester_name = htmlspecialchars($_POST['semester_name'] ?? '');
                $updated_start_date = htmlspecialchars($_POST['start_date'] ?? '');
                $updated_end_date = htmlspecialchars($_POST['end_date'] ?? '');

                // Basic validation
                if (empty($semester_id) || !is_numeric($semester_id) || $semester_id <= 0 || empty($updated_semester_name) || empty($updated_start_date) || empty($updated_end_date)) {
                    $_SESSION['error_message'] = "ข้อมูลไม่ครบถ้วนสำหรับการแก้ไขภาคการศึกษา";
                } else {
                    // Prepare SQL query to update the semester in the 'semesters' table
                    // Ensure column names match your 'semesters' table and the WHERE clause uses the correct ID column
                    $update_query = "UPDATE semester SET semester_name = ?, start_date = ?, end_date = ? WHERE id = ?";

                    // Prepare the statement
                    if ($stmt = $conn->prepare($update_query)) {
                        // Bind parameters
                        // 'sssi' indicates 3 strings and 1 integer (the ID)
                        // Adjust types based on your database column types if needed
                        $stmt->bind_param("sssi", $updated_semester_name, $updated_start_date, $updated_end_date, $semester_id);

                        // Execute the statement
                        if ($stmt->execute()) {
                            // Check if any row was actually updated
                            if ($stmt->affected_rows > 0) {
                                $_SESSION['success_message'] = "แก้ไขภาคการศึกษาสำเร็จแล้ว";
                            } else {
                                // This might mean the data was the same, or the ID wasn't found
                                $_SESSION['success_message'] = "ไม่มีการเปลี่ยนแปลงข้อมูล หรือไม่พบภาคการศึกษาที่ต้องการแก้ไข";
                            }
                        } else {
                            $_SESSION['error_message'] = "เกิดข้อผิดพลาดในการแก้ไขภาคการศึกษา: " . $stmt->error;
                        }

                        // Close statement
                        $stmt->close();
                    } else {
                        $_SESSION['error_message'] = "เกิดข้อผิดพลาดในการเตรียมคำสั่งฐานข้อมูล (แก้ไขภาคการศึกษา): " . $conn->error;
                    }
                }
                break;

            case 'delete':
                // --- Handle Delete Semester Action ---
                // Get the semester ID from the form (from manage_semesters.php table)
                $semester_id = $_POST['semester_id'] ?? null; // Name from the hidden input in the delete form

                // Basic validation
                if ($semester_id === null || !is_numeric($semester_id) || $semester_id <= 0) {
                    $_SESSION['error_message'] = "ไม่พบรหัสภาคการศึกษาที่ต้องการลบ หรือรหัสไม่ถูกต้อง";
                } else {
                    // Prepare SQL query to delete a semester from the 'semesters' table
                    // Ensure the WHERE clause uses the correct ID column (assuming 'id')
                    $delete_query = "DELETE FROM semester WHERE id = ?"; // Delete based on 'id' column

                    // Prepare the statement
                    if ($stmt = $conn->prepare($delete_query)) {
                        // Bind parameter (assuming semester ID is integer)
                        $stmt->bind_param("i", $semester_id);

                        // Execute the statement
                        if ($stmt->execute()) {
                            // Check if any row was actually deleted
                            if ($stmt->affected_rows > 0) {
                                $_SESSION['success_message'] = "ลบภาคการศึกษาสำเร็จแล้ว";
                            } else {
                                $_SESSION['error_message'] = "ไม่พบภาคการศึกษาที่ต้องการลบ (อาจถูกลบไปแล้ว)";
                            }
                        } else {
                            $_SESSION['error_message'] = "เกิดข้อผิดพลาดในการลบภาคการศึกษา: " . $stmt->error;
                        }

                        // Close statement
                        $stmt->close();
                    } else {
                        $_SESSION['error_message'] = "เกิดข้อผิดพลาดในการเตรียมคำสั่งฐานข้อมูล (ลบภาคการศึกษา): " . $conn->error;
                    }
                }
                break;

            default:
                // Handle unknown action
                $_SESSION['error_message'] = "การดำเนินการไม่ถูกต้อง";
                break;
        }

        // Close database connection after all operations are done
        if (isset($conn) && $conn) {
            $conn->close();
        }

    } else {
        // 'action' parameter is not set
        $_SESSION['error_message'] = "ไม่ระบุการดำเนินการ";
    }

    // Redirect back to the manage semesters page after processing
    // *** ตรวจสอบพาธนี้ให้ถูกต้องตามโครงสร้างโฟลเดอร์ของคุณ ***
    header("Location: ../admin/manage_semesters.php");
    exit();

} else {
    // If the request method is not POST, redirect to the manage semesters page
    // or an error page
    // *** ตรวจสอบพาธนี้ให้ถูกต้องตามโครงสร้างโฟลเดอร์ของคุณ ***
    header("Location: ../admin/manage_semesters.php");
    exit();
}
?>
